### ISSUE TITLE
Loose regex does not properly find ISBN

### ISSUE THREAD

**Issue by jproffitt** [xlcnd/isbnlib#10]
Consider the ISBN string `'978-0-07-879984-6'`. I know thats technically not a valid isbn, but I have encountered strings like this many times.

If I run `get_isbnlike` in normal mode:

    isbnlib.get_isbnlike('978-0-07-879984-6', 'normal')

I get `['978-0-07-879984-6']`. That's good. But when I run in loose mode:

    isbnlib.get_isbnlike('978-0-07-879984-6', 'loose')

I get `['978-0-07-879984-']`. Notice the missing 6 on the end. You would think that loose mode would catch just as many valid isbn's as normal mode would, or more. But it doesn't.

I'm not quite sure what the best solution is, but the source of the problem is the `RE_LOOSE` regex. It checks only for numbers and dashes 10-16 characters long. A simple solution would be to just increase that to 18 or something like that.

**Comment by xlcnd** [comment]
Done in release v3.4.3
