### ISSUE TITLE
wildcard ISBN search?

### ISSUE THREAD

**Issue by fredzannarbor** [xlcnd/isbnlib#105]
Hello, 

is it possible to do wildcard searches to find  [ISBNs with particular prefixes](url), e.g. Ukraine = 978-617*? . Is it then possible to sort them by ISBN issue date, so as to get the latest books published in that region?

**Comment by xlcnd** [comment]
Thanks. The short answer is NO! The only general source for this information is Google Books API and I don't see how implement this feature with the current version of the API.

**Comment by fredzannarbor** [comment]
THanks!
