### ISSUE TITLE
GitHub Action: coverage is not running on pytest

### ISSUE THREAD

**Issue by cclauss** [xlcnd/isbnlib#111]
In our upgrade from nose to pytest, coverage was disabled in our GitHub Action.  Please re-enable [coverage](https://pypi.org/project/coverage/) so it works as it did with nose.  Also, please ensure that the coverage-related instructions in `CONTRIBUTING.md` are correct.
* #108

**Comment by xlcnd** [comment]
It works locally but not on Github! For now, I don't have time to investigate...

**Comment by xlcnd** [comment]
Is running now!

**Comment by cclauss** [comment]
Well done!  Thanks.
