### ISSUE TITLE
[Enhancement] `meta` be able to ignore ISBNNotConsistentError

### ISSUE THREAD

**Issue by athossampayo** [xlcnd/isbnlib#117]
Regarding the use of `meta()`:

There are times where a different ISBN is returned internally and `ISBNNotConsistentError` is raised, but is referent to the same book and the user might want to ignore the error and use the data found, but right now this is not possible, not even by capturing the exception.

Maybe we should add the metadata on this exception class?

One ISBN example that I found on the wild were would be useful to use the data returned:
```
isbnlib.dev._exceptions.ISBNNotConsistentError: isbn request != isbn response (9788487169021 not in [{'type': 'ISBN_10', 'identifier': '8487169007'}, {'type': 'ISBN_13', 'identifier': '9788487169007'}])
```

**Comment by xlcnd** [comment]
HI.

The problem is that the data returned is not always for the same book! Sometimes, the data belongs to another 'related' book. So in order to maintain data integrity, this exception **must** be raised.

**Comment by athossampayo** [comment]
@xlcnd that makes sense, but could the exception class receive the returned data as an attribute so the user can decide to capture it when needed to ignore? WDYT?
