### ISSUE TITLE
Add a network pytest mark for tests that use the network

### ISSUE THREAD

**Issue by mcepl** [xlcnd/isbnlib#121]
**Is your feature request related to a problem? Please describe.**
Sometimes it's useful to have the tests that use the network marked so they can be skipped easily when we know the network is not available.

This is useful for example on SUSE and openSUSE's build servers. When building our packages the network is disabled so we can assure reproducible builds (among other benefits). With this mark, it's easier to skip tests that can not succeed.

**Describe the solution you'd like**
[suggested patch](https://github.com/xlcnd/isbnlib/files/10609889/mark-network-tests.patch.txt)

**Comment by xlcnd** [comment]
Hi thanks.

Yes, it's a very good idea!
