### ISSUE TITLE
Handle formatted ISBNs gracefully (or throw an error)

### ISSUE THREAD

**Issue by EmilStenstrom** [xlcnd/isbnlib#14]
I tried converting some ISBNs like this:
```python
>>> import isbnlib
>>> isbnlib.to_isbn13("91-43-01019-9")
'91-43-01019-9'
```
Huh? That doesn't look like an ISBN13? After some thinking it seems I should have stripped the dashes before trying to convert: 
```python
>>> isbnlib.to_isbn13("9143010199")
'9789143010190'
```
But then again I lose the dashes, that makes ISBNs more readable. 

I would have expected the first version to work, and give me a formatted ISBN13 back (like on [ISBN.org converter](http://www.isbn.org/ISBN_converter)). 

Or am I simply doing it wrong?

**Comment by xlcnd** [comment]
`isbnlib` works mainly with striped ISBNs, it is faster and more useful in most of the operations...
But you can always get a 'masked' isbn by using `isbnlib.mask(isbn13)`. 

However, the first example you gave is a regression bug, I will fix it in the next version!

Thanks.

**Comment by EmilStenstrom** [comment]
I see! Then maybe it would be a good idea to tell people about that from the start.

Can I suggest you add a couple of usage examples to the top of the README? Some with dashes and some without. Would help beginner like med get started quickly.

**Comment by xlcnd** [comment]
OK! I will put some examples. 

By the way, these core functions that transform, clean, extract, ... ISBNs, usually don't throw exceptions, if something don't applies they return None.

**Comment by EmilStenstrom** [comment]
Excellent! Thanks. I think it will make this library easier to get started with!

**Comment by xlcnd** [comment]
Thanks.
