### ISSUE TITLE
Wrong meta with a ISBN number not found

### ISSUE THREAD

**Issue by mirelsol** [xlcnd/isbnlib#16]
>>> import isbnlib
    >>> isbnlib.__version__
    '3.4.7'
    >>> isbnlib.meta('9788806219345') # No results
    >>> isbnlib.meta('9782754003254') # Ok
    {'ISBN-13': '9782754003254', 'Language': 'ita', 'Publisher': 'First Editions', 'Year': '2007', 'Authors': ['Francesca Romana Onofri', 'Karen Antje Möller'], 'Title': "L'italien pour les nuls"}
    >>> isbnlib.meta('9788806219345') # Wrong we get the same result as for ISBN 9782754003254
    {'ISBN-13': '9782754003254', 'Language': 'ita', 'Publisher': 'First Editions', 'Year': '2007', 'Authors': ['Francesca Romana Onofri', 'Karen Antje Möller'], 'Title': "L'italien pour les nuls"}

Is it a cache problem?

**Comment by xlcnd** [comment]
Are you using the default caching?

**Comment by xlcnd** [comment]
It is a bug!

I will fix it for the next release (next few days).

Thanks.

**Comment by xlcnd** [comment]
**Solved**! The secondary cache wasn't properly cleared.

**NOTE** Keep the issue open while not new release.
