### ISSUE TITLE
isbnlib.meta() no longer works with unicode input

### ISSUE THREAD

**Issue by jbaiter** [xlcnd/isbnlib#20]
```
In [11]: isbnlib.meta(u"2266202022", service="merge")
In [11]: isbnlib.meta(u"2266202022", service="wcat")
#....
/home/jojo/.envs/spreads/local/lib/python2.7/site-packages/isbnlib/_wcat.pyc in _mapper(isbn, records)
     30     except:  # pragma: no cover
     31         LOGGER.debug("RecordMappingError for %s with data %s", isbn, records)
---> 32         raise RecordMappingError(isbn)
     33     # call stdmeta for extra cleanning and validation
     34     return stdmeta(canonical)

RecordMappingError: the mapping `canonical <- records` doesn't work (9782266202022)
```

When digging around in the stack trace a bit, it seems that the services actually did return the correct metadata, isbnlib just can't produce a proper mapping for it.
I am using the latest version from PyPi (3.5.3).

*Update:*
I did some more digging, and the problem only seems to occur when I pass the ISBN as an `unicode` instance. The underlying exception is this:

```
isbnlib._wcat: decoding Unicode is not supported
Traceback (most recent call last):
  File "/home/jojo/.envs/spreads/local/lib/python2.7/site-packages/isbnlib/_wcat.py", line 23, in _mapper
    canonical['ISBN-13'] = u(isbn)
  File "/home/jojo/.envs/spreads/local/lib/python2.7/site-packages/isbnlib/dev/bouth23.py", line 19, in u
    return unicode(x, "utf-8")
TypeError: decoding Unicode is not supported
```

**Comment by xlcnd** [comment]
ISBN is by definition an ASCII string so I don't see the need for unicode... However, `isbnlib` transforms every input to unicode (only in python 2, in python 3 they are already unicode!). 

So to make things easier and work as expected in Python 2 and 3 simple don't use the u"" operator.

Thanks.

**Comment by xlcnd** [comment]
By the way, in the next version of `isbnlib` I am planning to change the behaviour of the `u()` function so that, in python 2, if the input is already unicode it does nothing (and so it will not raise an exception)! 

Then your example will work.

**Comment by jbaiter** [comment]
:+1:
