### ISSUE TITLE
Formatting metadata

### ISSUE THREAD

**Issue by knutshub** [xlcnd/isbnlib#24]
Thanks a lot for this python package. I'm using it for a small project at the moment.

But I'm struggling with changing the metadata output. 

    meta(isbn, service='default', cache='default')

    With isbnlib.registry you can change the metadata service to be used by default (setdefaultservice), 
    add a new service (add_service), access bibliographic formatters for metadata (bibformatters), set 
    the default formatter (setdefaultbibformatter), add new formatters (add_bibformatter) and set a new 
    cache (set_cache) (e.g. to switch off the chache set_cache(None)). The cache only works for calls 
    through isbnlib.meta. These changes only work for the ‘current session’, so should be done always 
    before calling other methods.

I want to change the output to bibtex. But I'm not sure, what I have to do.

Do you can point me in the right direction, please?

Thanks in advance!

**Comment by xlcnd** [comment]
With metadata services you get 'unformated' metadata!

To format metadata, you need to  use `fmtbib` from `isbnlib.dev.helpers`.

Take a look at https://github.com/xlcnd/isbntools/blob/master/isbntools/bin/meta.py  for an example.

**Comment by xlcnd** [comment]
Another way is to use `bibformatters` from the `registry`, e.g.:

`from isbnlib import registry`, then `print(registry.bibformatters['bibtex'](metadata))` 

where `metadata` contains the metadata that you want to format.

**Comment by knutshub** [comment]
Thanks a lot for your fast response and help!

But unfortunately, I hadn't time to try it yesterday. I will do it today.
