### ISSUE TITLE
Fetching BibTeX meta is not clear in the doc

### ISSUE THREAD

**Issue by Phyks** [xlcnd/isbnlib#29]
Hi,

According to the doc, I can think of two ways to get a BibTeX metadata for a given ISBN:

* Either `meta(isbn)` and formatting it.
* Either `doi2tex(doi(isbn))`.

The second method seems to be more reliable, in particular as it relies on the DOI system, which is using a unique identifier and gives better results than `meta` in my experience.

However, taken from [https://www.doi.org/factsheets/ISBN-A.html](the ISBN-A page on doi.org), they say:

> ISBN-As do not automatically exist for every ISBN; they exist only once the agency has registered them in the DOI System.

Whereas when looking at [your code](https://github.com/xlcnd/isbnlib/blob/master/isbnlib/_ext.py#L47) you always derive an ISBN-A from a given ISBN13.

For my use case, I would need a way to check whether the generated ISBN-A is indeed a valid ISBN-A linked to any DOI or not. And reading the doc and looking a bit at the code, I was not sure what is the expected behavior of `doi2tex(doi(isbn))` when the ISBN-A does not exist.

Thanks a lot!

P.S.: As I do not have examples of ISBNs without associated ISBN-A, I cannot check this easily =( Sorry if this is already documented somewhere else.

**Comment by xlcnd** [comment]
`doi2tex(doi(isbn))` will return nothing if the corresponding ISBN-A wasn't issued yet.

In relation to valid ISBN-A and registed ISBN-A, please see the Note (https://github.com/xlcnd/isbnlib#note) about valid and issued ISBNs...

**Comment by Phyks** [comment]
Thanks! I was not sure about the value returned in such cases.
