### ISSUE TITLE
xISBN decommission

### ISSUE THREAD

**Issue by grahamalama** [xlcnd/isbnlib#51]
The xID service [used by isbnlib](https://github.com/xlcnd/isbnlib/blob/d3deee557e7197c28b4cd572cff169d1672d49a7/isbnlib/_wcat.py) for WorldCat metadata lookup [is being decommissioned](https://www.oclc.org/developer/news/2018/xid-decommission.en.html).

One possible workaround for this is to use the [Classify - ClassificationResource Read](https://platform.worldcat.org/api-explorer/apis/Classify/ClassificationResource/Read) to convert an ISBN to an OCLC identifier, then use the [WorldCat Metadata API - bib Read](https://platform.worldcat.org/api-explorer/apis/WorldCatMetadataAPI/bib/Read) (which uses an OCLC number) to retrieve the metadata. It looks like this might require WorldCat credentials, though?

**Comment by xlcnd** [comment]
Again...! It is time to **drop support for WorldCat**.

**Comment by jessielearned** [comment]
What about ISBNdb?

**Comment by xlcnd** [comment]
A new plugin [isbnlib_oclc](https://github.com/xlcnd/isbnlib_oclc) is available that pulls data from WorldCat.

**This is the most complete set of books metadata.**
