### ISSUE TITLE
The description and Cover feature don't seem to work

### ISSUE THREAD

**Issue by Gammaslah132** [xlcnd/isbnlib#57]
The Bug:
When I ran a program I made to that finds the details of the ISBN, a description, and a cover of it. The cover and description functions didn't work and I got this big long error message which I screenshotted below. 

My code was:
```
from isbnlib import meta, desc, cover
Service = 'openl'
ISBN = input("What is your ISBN number (no spaces) ")
book = meta(ISBN, Service)
print(book)
print(desc(ISBN))
bookCover = cover(ISBN)
```

Screenshot of Error:
<img width="830" alt="Screen Shot 2019-04-25 at 12 20 13 PM" src="https://user-images.githubusercontent.com/49981009/56729455-a20aab00-6755-11e9-9fd2-be5ccef5f22f.png">
<img width="987" alt="Screen Shot 2019-04-25 at 12 20 21 PM" src="https://user-images.githubusercontent.com/49981009/56729456-a20aab00-6755-11e9-86ef-4fac32254b7a.png">

Computer info:
 - OS: [Mac]
 - Python version [3.6]
 - isbnlib version [3.9.6]

If this isn't a bug and an error on my part I would love to know what I did wrong.

**Comment by xlcnd** [comment]
Are you in a very slow internet connection?

**Comment by Gammaslah132** [comment]
Does that affect how the feature works?

**Comment by Gammaslah132** [comment]
Let me try it somewhere with better internet and I will let you know if that fixed it

**Comment by xlcnd** [comment]
Yes, if your connection is very slow it timeout...

**Comment by Gammaslah132** [comment]
Tried with faster internet and same result

**Comment by xlcnd** [comment]
This is not a problem with 'isbnlib', it is a problem with your connection OR python installation.

**Comment by Gammaslah132** [comment]
I see any recommendations on what to do then

**Comment by xlcnd** [comment]
Try with a different version of python.

**Comment by xlcnd** [comment]
You could check [here](https://travis-ci.org/xlcnd/isbnlib/builds/523972805) that `isbnlib` is working OK.

By the way, what operating system are you using?

**Comment by Gammaslah132** [comment]
Mac

**Comment by xlcnd** [comment]
Check the firewall settings.

**Comment by Gammaslah132** [comment]
Also, I'm using Python 3.6 and Pycharm

**Comment by Gammaslah132** [comment]
Doesn't seem to work I tried changing the python version and looked at firewall settings.

**Comment by Gammaslah132** [comment]
How fast would my internet to be for it to work?

**Comment by xlcnd** [comment]
You don't need a fast internet... ìsbnlib` gives 10 seconds to the connection to be establish (only a very **very** slow internet needs more than that)!

Something (?!) is blocking the handshake with the Google services, but is **not related** with `isbnlib`.

**Comment by Gammaslah132** [comment]
Hmmm wonder what that could be

**Comment by Gammaslah132** [comment]
Does the isbnlib connect to your default browser?

**Comment by xlcnd** [comment]
Looking at your script I see that you are using service 'openl' to get the metadata. Did it work?

**Comment by Gammaslah132** [comment]
I got the metadata using openl. I got all the book info from the ISBN.

**Comment by xlcnd** [comment]
`isbnlib`doesn't use the browser...

**Comment by Gammaslah132** [comment]
Ok was just checking to see if that might be the issue

**Comment by xlcnd** [comment]
Can I have the ISBN that you are using?

**Comment by Gammaslah132** [comment]
9780590353427

**Comment by xlcnd** [comment]
The description is:

 _Rescued from the outrageous neglect of his aunt and uncle, a young boy with
 a great destiny proves his worth while attending Hogwarts School for
 Witchcraft and Wizardry._

And the links to the cover are:

**smallThumbnail:**  http://books.google.com/books/content?id=fo4rzdaHDAwC&printsec=frontcover&img=1&zoom=5&source=gbs_api
**thumbnail:**  http://books.google.com/books/content?id=fo4rzdaHDAwC&printsec=frontcover&img=1&zoom=1&source=gbs_api

**Comment by xlcnd** [comment]
In what part of the world you are?

**Comment by Gammaslah132** [comment]
Thanks but I was trying to create a program that allows the user to give a ISBN and then the program gives it to them. Europe

**Comment by xlcnd** [comment]
Maybe it is only a problem with Google Books services for your country... that happens and usually after I couple of hours the problem is gone.

**Comment by Gammaslah132** [comment]
Should I try not using openL

**Comment by Gammaslah132** [comment]
I got it to work by using this code I found from this website:http://blog.pengyifan.com/how-to-fix-python-ssl-certificate_verify_failed/

`import os, ssl
if (not os.environ.get('PYTHONHTTPSVERIFY', '') and
    getattr(ssl, '_create_unverified_context', None)): 
    ssl._create_default_https_context = ssl._create_unverified_context`

**Comment by Gammaslah132** [comment]
Thank you for your help though
