### ISSUE TITLE
isbnlib.meta() causes ISBNLibURLError

### ISSUE THREAD

**Issue by reno** [xlcnd/isbnlib#59]
I'm trying to use isbnlib.meta() and it raises an ISBNLibURLError exception, caused by
```
"isbnlib/_imcache.py", line 26, in __getitem__
    return self.d[k]
KeyError: '9781585109043default' 
```

Should be simple to reproduce:
```
import isbnlib

isbn = '9781491946008'
isbnlib.meta(isbn) 
```

The same error happens if I use a different service (e.g: 'worldcat'), except for 'loc'. The last just returns an empty dict. 

I'm running OSX 10.12, python 3.7.3 and installed isbnlib inside a venv enviroment using `pip install isbnlib`.

Thank you.

**Comment by xlcnd** [comment]
Hi, thanks.

I am not able to reproduce the error! From `isbnlib.meta('9781491946008')` I just got

```
{'ISBN-13': '9781491946008', 'Title': 'Fluent Python', 'Authors': ['Luciano Ramalho'], 
'Publisher': "O'Reilly Media", 'Year': '2015', 'Language': 'en'}
```
The empty dict from 'loc' is expected, probably they don't have books about computer programming in the Library of Congress...
 
What version of `isbnlib` are you using?

**Comment by xlcnd** [comment]
What is the error message returned by `ISBNLibURLError` exception?

**Comment by reno** [comment]
Hi, thanks for your feedback! I'm using version 3.9.8 of isbnlib.

So the exception message is `ISBNLibURLError: an URL error has ocurred ([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056))` .

I tried to set the enviroment variable `PYTHONHTTPSVERIFY=0`, then I get the exception: `ISBNLibURLError: an URL error has ocurred ([Errno 65] No route to host)`

**Comment by reno** [comment]
Searching about this last error message I found about self signing python. I followed [these steps](https://www.darklaunch.com/2014/02/02/fix-do-you-want-the-application-python-to-accept-incoming-network-connections) and it's working now! Thanks again

**Comment by xlcnd** [comment]
Thanks. I will left this issue open for a while so that people with similar problems can make use of it.
