### ISSUE TITLE
clarify license

### ISSUE THREAD

**Issue by dotlambda** [xlcnd/isbnlib#77]
`COPYRIGHT.txt` says
https://github.com/xlcnd/isbnlib/blob/28dff4414ec80d947afef20fd358fb2793e6873c/COPYRIGHT.txt#L5-L8

while [`LICENSE-LGPL-3.0-only.txt`](https://github.com/xlcnd/isbnlib/blob/dev/LICENSE-LGPL-3.0-only.txt) suggests only version 3.0 applies. Please clarify.

**Comment by xlcnd** [comment]
The two files match each other! Please, read https://www.gnu.org/licenses/gpl-howto.en.html

**Comment by dotlambda** [comment]
But the filename is very confusing. It suggests that only version 3.0 applies.

**Comment by xlcnd** [comment]
I change the name to LICENSE-LGPL-3.0-or-later.txt, using the correspondent SPDX identifier. From a legal point of view this changes **nothing**! Licenses have always **one** version, is the copyright notice (COPYRIGHT.txt) that establishes the acceptable versions...

**Comment by xlcnd** [comment]
In fact, it isn't a good idea to put the SPDX identifier in the name of the LICENSE, I will keep the name as LICENSE-LGPL-3.0.txt and put the SPDX identifier inside the COPYRIGHT.txt.

**Comment by dotlambda** [comment]
@xlcnd Thanks a lot! And of course you're right about the legal aspect.
