### ISSUE TITLE
isbn_from_words - an HTTP error has ocurred (429 Are you making many requests?)

### ISSUE THREAD

**Issue by ericluo04** [xlcnd/isbnlib#81]
Hello - I'm facing a similar error as #69. I believe the error comes from too many calls to `isbn_from_words` and not `meta`. Is there any in-package functionality to address this (i.e. scraping in large batches)? Or do you have any guidance on which API this function is using, so I can use `time.sleep` appropriately? Thanks so much!

**Comment by xlcnd** [comment]
This error happens because you are calling `meta` more than one time per second (see [webservice](https://github.com/xlcnd/isbnlib/blob/dev/isbnlib/dev/webservice.py))! To avoid this, you **must** throttle the **global** calls to `meta` for your machine.

**Comment by xlcnd** [comment]
Thanks.
