### ISSUE TITLE
Getting canonical of strangely formatted isbns can throw errors, even if they pass notisbn check

### ISSUE THREAD

**Issue by davidscotson** [xlcnd/isbnlib#82]
I noticed this on the following test input: "978-1-4342-9635/1" which is a valid isbn 13, except the last - is replaced with a / instead.

I was using isbnlib.notisbn(isbn) which says this is a valid isbn, because it runs canonical first, which strips out the / and just leaves the numbers. But then I was passing it onto get_canonical_isbn and it was hitting an error because the regex that it uses does the match first (finding:  <re.Match object; span=(0, 15), match='978-1-4342-9635'> and then passes that to canonical, which returns an empty string since there is only 12 numerical digits left.

I feel like this line: https://github.com/xlcnd/isbnlib/blob/dev/isbnlib/_core.py#L229 should check the return from canonical, to ensure it's not an empty string before continuing. It probably can't fail on properly formatted ISBNs, but it would be nice for it not to error even if you pass in badly formatted input.

**Comment by xlcnd** [comment]
Thank you.

I need to clarify the purpose of some methods and functions:
1. `notisbn` is used to discharge isbn-like strings with low probability of being valid ISBNs, it **doesn't validate** ISBNs.
2. `get_canonical_isbn` is used to extract ISBNs in the canonical form when the isbn-like string have high probability of being valide ISBNs.

These functions are usually used in batch jobs and **as alternatives**.

Anyway, I agree with the check in line https://github.com/xlcnd/isbnlib/blob/dev/isbnlib/_core.py#L229.

**Comment by davidscotson** [comment]
Yep, that change looks good.
