### ISSUE TITLE
editions() returns incorrect isbns when Open Library service is used

### ISSUE THREAD

**Issue by acidtv** [xlcnd/isbnlib#87]
It seems the `editions()` call with the Open Library service returns ISBNs from other books.

Example:
```python
>>> import isbnlib
>>> isbnlib.meta("9780596007126")
{'ISBN-13': '9780596007126', 'Title': 'Head First Design Patterns', 'Authors': ['Eric Freeman', 'Elisabeth Freeman', 'Kathy Sierra', 'Bert Bates'], 'Publisher': "O'Reilly Media, Inc.", 'Year': '2004', 'Language': 'en'}
>>> isbnlib.meta(isbnlib.editions("9780596007126", "openl")[1])
{'ISBN-13': '9788475335667', 'Title': 'Josafat', 'Authors': ['Prudenci Bertrana'], 'Publisher': '', 'Year': '1999', 'Language': 'ca'}
```

I'm using isbnlib 3.10.8 with python 3.9.7.

**Comment by mekarpeles** [comment]
Hi, please let us know if you have questions or need any help w/ Open Library's APIs

https://openlibrary.org/isbn/9780596007126.json is another way to get the json for this item.

**Comment by xlcnd** [comment]
Thanks mek. Soon, I will try with the new api.

**Comment by xlcnd** [comment]
For `isbnlib`, 'editions' is a list of *related* ISBNs (usually the same book but by another publisher), however after trying with the new API for Open Library, it seems that they don't have the same concept exposed by the API!

**Comment by mekarpeles** [comment]
For related isbns, you either want the isbns attached to the edition which you can get by adding .json to the edition url e.g. https://openlibrary.org/books/OL25448615M.json

Or you can get the isbns for related editions from the work (which spans editions) using the search API:
https://openlibrary.org/search.json?q=OL25448615M&fields=isbn

**Comment by xlcnd** [comment]
OK, I see! Then it is very easy to fix... it is now on 'dev'.
