### ISSUE TITLE
canonical(isbnlike) ignores lower-case x

### ISSUE THREAD

**Issue by psirotkin** [xlcnd/isbnlib#9]
Hi,

there are quite a lot of services out there using a lower-case x instead of an upper-case one in ISBN10. Unfortunately, canonical(isbnlike) just removes the x, thus rendering the ISBN invalid. I'm not really good at programming, so I solved the problem by modifying the function as follows:

    def canonical(isbnlike):
        """Keep only numbers and X."""
        numb = [c for c in isbnlike if c in '0123456789Xx']
        if numb[-1] == 'x':
            numb[-1] = 'X'
        return ''.join(numb)

...although there are probably more elegant or efficient ways of doing that.

**Comment by xlcnd** [comment]
Done in release v3.4.3

**Comment by psirotkin** [comment]
Great, thanks!
